version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_DSN=user:password@tcp(db:3306)/distnetdb?parseTime=true
      - ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: distnetdb
    ports:
      - "3306:3306"